<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pix.proto

namespace Pix;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pix.PixKeyListResponse</code>
 */
class PixKeyListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pix.PixKey pix_keys = 1;</code>
     */
    private $pix_keys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Pix\PixKey>|\Google\Protobuf\Internal\RepeatedField $pix_keys
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pix::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pix.PixKey pix_keys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPixKeys()
    {
        return $this->pix_keys;
    }

    /**
     * Generated from protobuf field <code>repeated .pix.PixKey pix_keys = 1;</code>
     * @param array<\Pix\PixKey>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPixKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pix\PixKey::class);
        $this->pix_keys = $arr;

        return $this;
    }

}

