<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pix.proto

namespace Pix;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pix.PixKeyModel</code>
 */
class PixKeyModel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string type = 2;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string key = 3;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>string bankISPB = 4;</code>
     */
    protected $bankISPB = '';
    /**
     * Generated from protobuf field <code>optional string belongsTo = 5;</code>
     */
    protected $belongsTo = null;
    /**
     * Generated from protobuf field <code>string createdAt = 6;</code>
     */
    protected $createdAt = '';
    /**
     * Generated from protobuf field <code>string updatedAt = 7;</code>
     */
    protected $updatedAt = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $type
     *     @type string $key
     *     @type string $bankISPB
     *     @type string $belongsTo
     *     @type string $createdAt
     *     @type string $updatedAt
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pix::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 2;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key = 3;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bankISPB = 4;</code>
     * @return string
     */
    public function getBankISPB()
    {
        return $this->bankISPB;
    }

    /**
     * Generated from protobuf field <code>string bankISPB = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBankISPB($var)
    {
        GPBUtil::checkString($var, True);
        $this->bankISPB = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string belongsTo = 5;</code>
     * @return string
     */
    public function getBelongsTo()
    {
        return isset($this->belongsTo) ? $this->belongsTo : '';
    }

    public function hasBelongsTo()
    {
        return isset($this->belongsTo);
    }

    public function clearBelongsTo()
    {
        unset($this->belongsTo);
    }

    /**
     * Generated from protobuf field <code>optional string belongsTo = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBelongsTo($var)
    {
        GPBUtil::checkString($var, True);
        $this->belongsTo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string createdAt = 6;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Generated from protobuf field <code>string createdAt = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->createdAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updatedAt = 7;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Generated from protobuf field <code>string updatedAt = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updatedAt = $var;

        return $this;
    }

}

